# Generated by Django 2.2.3 on 2019-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(max_length=10)),
                ('capacity', models.IntegerField(max_length=10)),
            ],
        ),
    ]
