# Generated by Django 2.2.3 on 2019-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
