# Generated by Django 2.2.3 on 2019-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190707_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
