# Generated by Django 2.2.3 on 2019-07-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_meetingroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='capacity',
        ),
    ]
