# Generated by Django 2.2.3 on 2019-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_meetingroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
