# Generated by Django 2.2.3 on 2019-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='r_number',
            field=models.IntegerField(),
        ),
    ]
