# Generated by Django 2.2.3 on 2019-07-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190715_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='r_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.MeetingRoom'),
        ),
    ]
