# Generated by Django 2.2.3 on 2019-07-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190716_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='r_number',
            new_name='room_number',
        ),
    ]
