# Generated by Django 2.2.3 on 2019-07-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190716_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_number',
            new_name='r_number',
        ),
    ]
